//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        public int Id { get; set; }
        public string Id_furniture { get; set; }
        public int Room { get; set; }
        public int Year { get; set; }
    }
}
